CREATE DATABASE firstapi;

CREATE TABLE IF NOT EXISTS public.appweb_empleado
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    correo character varying(254) COLLATE pg_catalog."default" NOT NULL,
    apellido character varying(100) COLLATE pg_catalog."default" NOT NULL,
    contrasena character varying(255) COLLATE pg_catalog."default" NOT NULL,
    especialidad character varying(100) COLLATE pg_catalog."default" NOT NULL,
    nombre character varying(100) COLLATE pg_catalog."default" NOT NULL,
    telefono character varying(15) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT appweb_empleado_pkey PRIMARY KEY (id),
    CONSTRAINT appweb_empleado_correo_key UNIQUE (correo)
)